### ISSUE TITLE
[PE-D] “clear -p all” cannot work properly, it will just clear everything

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-4/tp#156] opened 2021-10-31 07:38 UTC
![image.png](https://raw.githubusercontent.com/HolmesJJ/ped/main/files/e320ae96-59eb-47a3-a3aa-ef12467565f6.png)

Bug description
1. “clear -p all” cannot work properly, it will just clear everything.

Suggestion
1. Need to fix the logic of the “clear” feature.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: HolmesJJ/ped#16

**Comment by IceWizard4902** [comment] 2021-10-31 08:35
This is not a functionality bug, rather it is a documentation bug.

The command is functioning correctly, the `all` range is supposed to clear out every entries in the list specified by the flags given in the input.

The only problem here is the wording of the member list. I used the word `person` to represent the member of the IG. This indeed causes confusion to the user (as it is different from the name given in the tab above).

This should be resolved by changing `person` to `member`. The feature is working as intended.

**Closed** 2021-10-31 09:19 UTC
